const members = require('./members/members.service.js')
const topics = require('./topics/topics.service.js')
const favoriteTopic = require('./favorite-topic/favorite-topic.service.js')
const reports = require('./reports/reports.service.js')
const commentsMember = require('./comments-member/comments-member.service.js')
const events = require('./events/events.service.js')
const registerEvent = require('./register-event/register-event.service.js')
const sendEmail = require('./send-email/send-email.service.js')
const eventsNotify = require('./events-notify/events-notify.service.js')
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(members)
  app.configure(topics)
  app.configure(favoriteTopic)
  app.configure(reports)
  app.configure(commentsMember)
  app.configure(events)
  app.configure(registerEvent)
  app.configure(sendEmail)
  app.configure(eventsNotify)
}
